blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from about_me import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_page)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about_me/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank = True)

    def __str__(self):
        return self.title

blog/models.py
from django.db import models

class Blog_project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    date = models.DateField()

    def __str__(self):
        return self.title

about_me/views.py
from django.shortcuts import render
from .models import Project

def main_page(request):
    projects = Project.objects.all()
    return render(request, 'about_me/main.html', {'projects':projects})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog_project

def all_blogs(request):
    blogs = Blog_project.objects.all()
    #для ограничения постов писать order_by('-date')[:5] (сортировка по дате)
    return render(request,'blog/all_blogs.html',{'blogs':blogs})
def detail(request,blog_id):
    blog = get_object_or_404(Blog_project,pk = blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

about_me/templates/about_me/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% load static %}
    <a href = "{% url 'blog:all_blogs' %}"><p>blog part</p></a>
    <div class = 'container text-center'>
        <h1>its main page</h1>
        <a href = "{%static 'about_me/textresume.pdf'%}">Resume</a>
        <img src ="{% static 'about_me/ghoul.png' %}">
        {% for project in projects %}
            <h2>{{ project.title }}</h2>
            <p>{{ project.description }}</p>
            <img src = "{{ project.image.url }}" height=40 width=40>
            {% if project.url %}
                <a href ="{{ project.url }}">Link </a>
            {% endif %}
        {% endfor %}
</body>
</html>

blog/templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class ='container text-center'>
    <h1>Klim written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>
    {% for blog in blogs %}
        <a href = "{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
        <p>{{ blog.date|date:'M d Y' }}</p>
        <p>{{ blog.description|striptags|truncatechars:100 }}</p>
    {% endfor %}
    </div>
</body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ blog.title }}<br>
    <h2>--{{ blog.date|date:'F jS Y' }}--</h2>
    {{ blog.description|safe}}
</body>
</html>